---
- name: Apt Update Cache
  apt: update_cache=yes

- name: Install make
  apt: pkg=make state=present update_cache=yes

- name: Install libcurl4-gnutls-dev
  apt: pkg=make state=present

- name: Install Java
  apt: pkg=openjdk-7-jre-headless state=present
